/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.
    glossary.data.xmlBindingSubclasses;

import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementLinkTarget;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.glossary.data.xmlBinding.ViewElementLinkTarget;

public class FLGGlossaryElementLinkTarget
    extends ViewElementLinkTarget
    implements FSLLearningUnitViewElementLinkTarget {
}
