/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.
    glossary.data.xmlBindingSubclasses;

import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementLink;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementLinkTarget;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementsManager;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.glossary.data.xmlBinding.ViewElementLink;

public class FLGGlossaryElementLink
    extends ViewElementLink
    implements FSLLearningUnitViewElementLink {
  public FSLLearningUnitViewElementLinkTarget
      addNewLearningUnitViewElementLinkTarget(String learningUnitId,
                                              String learningUnitViewManagerId,
                                              String learningUnitViewElementId) {
    FLGGlossaryElementLinkTarget learningUnitViewElementLinkTarget = new
        FLGGlossaryElementLinkTarget();
    return FSLLearningUnitViewElementsManager.
        addLearningUnitViewElementLinkTarget(this,
                                             learningUnitViewElementLinkTarget,
                                             learningUnitId,
                                             learningUnitViewManagerId,
                                             learningUnitViewElementId);
  }
}
