// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.messaging;

/**
 * @see org.openuss.messaging.Message
 */
public class MessageImpl
    extends org.openuss.messaging.MessageBase
	implements org.openuss.messaging.Message
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -1396399022084794986L;

}