// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.lecture;

/**
 * @see org.openuss.lecture.Organisation
 */
public abstract class OrganisationImpl
    extends org.openuss.lecture.OrganisationBase
	implements org.openuss.lecture.Organisation
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 391078913590423980L;

}