// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package org.openuss.lecture;

/**
 * @see org.openuss.lecture.Period
 */
public class PeriodImpl extends org.openuss.lecture.PeriodBase implements org.openuss.lecture.Period {
	/**
	 * The serial version UID of this class. Needed for serialization.
	 */
	private static final long serialVersionUID = 9086031628022698697L;

	@Override
	public void add(Course course) {
		getCourses().add(course);
	}

	@Override
	public void remove(Course course) {
		getCourses().remove(course);
	}

	@Override
	public boolean isActive() {
		return getFaculty() != null && equals(getFaculty().getActivePeriod());
	}

}