/* Generated by FreestyleLearninngGroup */

package freestyleLearning.homeCore.learningUnitsManager.data.xmlBindingSubclasses;

import freestyleLearning.homeCore.learningUnitsManager.data.xmlBinding.EditStatus;

public class FSLEditStatus extends EditStatus {
}
