// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.chat;

/**
 * @see org.openuss.chat.ChatMessage
 */
public class ChatMessageImpl
    extends org.openuss.chat.ChatMessageBase
	implements org.openuss.chat.ChatMessage
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -3214203643011700654L;

}