// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.chat;

/**
 * @see org.openuss.chat.ChatUser
 */
public class ChatUserImpl
    extends org.openuss.chat.ChatUserBase
	implements org.openuss.chat.ChatUser
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6995233571590067792L;

}