// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.seminarpool;

/**
 * @see org.openuss.seminarpool.CourseGroup
 */
public class CourseGroupImpl
    extends org.openuss.seminarpool.CourseGroupBase
	implements org.openuss.seminarpool.CourseGroup
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5256797015565690286L;

	@Override
	public void addUser(Long userId) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void removeUser(Long userId) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void addCourseSchedule(CourseSchedule courseSchedule) {
    	if ( !getCourseSchedule().contains(courseSchedule) ) {
    		getCourseSchedule().add(courseSchedule);
    	}
    	courseSchedule.setCourseGroup(this);	
    }

	@Override
	public void removeCourseGroup(CourseSchedule courseSchedule) {
		if (getCourseSchedule().remove(courseSchedule)) {
			if (courseSchedule.getCourseGroup().equals(this)) {
				courseSchedule.setCourseGroup(null);
			}
		}
	}

}