// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.seminarpool;

/**
 * @see org.openuss.seminarpool.SeminarCondition
 */
public class SeminarConditionImpl
    extends org.openuss.seminarpool.SeminarConditionBase
	implements org.openuss.seminarpool.SeminarCondition
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3868835974911873685L;

}