// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.collaboration;

/**
 * @see org.openuss.collaboration.CourseMemberWorkspace
 */
public class CourseMemberWorkspaceImpl
    extends org.openuss.collaboration.CourseMemberWorkspaceBase
	implements org.openuss.collaboration.CourseMemberWorkspace
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8001725359968498887L;

}