alter table PARTICIPANTS_COURSES drop constraint PARTICIPANTS_COURSES_COURSES_FKC;
alter table PARTICIPANTS_COURSES drop constraint PARTICIPANTS_COURSES_PARTICIPANTS_FKC;
drop table COURSE;
drop table PARTICIPANTS_COURSES;
drop table STUDENT;
drop generator GLOBAL_SEQUENCE;
create table COURSE (ID numeric(18,0) not null, NAME varchar(255) not null, primary key (ID));
create table PARTICIPANTS_COURSES (PARTICIPANTS_FK numeric(18,0) not null, COURSES_FK numeric(18,0) not null, primary key (COURSES_FK, PARTICIPANTS_FK));
create table STUDENT (MNR numeric(18,0) not null, FIRSTNAME varchar(255) not null, LASTNAME varchar(255) not null, BIRTHDAY timestamp not null, primary key (MNR));
alter table PARTICIPANTS_COURSES add constraint PARTICIPANTS_COURSES_COURSES_FKC foreign key (COURSES_FK) references COURSE;
alter table PARTICIPANTS_COURSES add constraint PARTICIPANTS_COURSES_PARTICIPANTS_FKC foreign key (PARTICIPANTS_FK) references STUDENT;
create generator GLOBAL_SEQUENCE;
