// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.buddylist;

/**
 * @see org.openuss.buddylist.BuddyList
 */
public class BuddyListImpl
    extends org.openuss.buddylist.BuddyListBase
	implements org.openuss.buddylist.BuddyList
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5896651731072914662L;

}