// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.buddylist;

/**
 * @see org.openuss.buddylist.InternalMessage
 */
public class InternalMessageImpl
    extends org.openuss.buddylist.InternalMessageBase
	implements org.openuss.buddylist.InternalMessage
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -8312132477770167834L;

}