/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing;

import java.awt.Image;
import java.io.File;

import javax.xml.bind.Dispatcher;

import freestyleLearning.learningUnitViewAPI.FSLAbstractLearningUnitViewManager;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewPrimaryActivationButton;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewXMLDocument;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewsActivator;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitsActivator;
import freestyleLearning.learningUnitViewAPI.events.learningUnitEvent.FSLLearningUnitEventGenerator;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.data.xmlBinding.LearningByDoingDescriptor;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.data.xmlBinding.ViewElement;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.data.xmlBinding.ViewElementLink;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.data.xmlBinding.ViewElementLinkTarget;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.data.xmlBindingSubclasses.FLGLearningByDoingDescriptor;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.data.xmlBindingSubclasses.FLGLearningByDoingElement;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.data.xmlBindingSubclasses.FLGLearningByDoingElementLink;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.data.xmlBindingSubclasses.FLGLearningByDoingElementLinkTarget;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.elementInteractionPanel.FLGLearningByDoingElementInteractionPanel;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.elementsContentsPanel.FLGLearningByDoingElementsContentsPanel;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.elementsStructurePanel.FLGLearningByDoingElementsStructurePanel;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.statusPanel.FLGLearningByDoingStatusPanel;
import freestyleLearningGroup.independent.gui.FLGImageUtility;
import freestyleLearningGroup.independent.util.FLGInternationalization;
import freestyleLearningGroup.independent.util.FLGLongLastingOperationStatus;

public class FLGLearningByDoingManager extends FSLAbstractLearningUnitViewManager {
    private FSLLearningUnitViewPrimaryActivationButton primaryActivationButton;
    private FLGInternationalization internationalization;

    public void init(FSLLearningUnitsActivator learningUnitsActivator,
        FSLLearningUnitViewsActivator learningUnitViewsActivator, FSLLearningUnitEventGenerator learningUnitEventGenerator,
        String learningUnitViewManagerId, String learningUnitViewManagerTitle, File learningUnitViewManagerCodeDirectory,
        boolean editMode, boolean originalElementsOnly, FLGLongLastingOperationStatus progressStatus) {
            super.init(learningUnitsActivator, learningUnitViewsActivator, learningUnitEventGenerator,
                learningUnitViewManagerId, learningUnitViewManagerTitle, learningUnitViewManagerCodeDirectory, editMode,
                originalElementsOnly, progressStatus);
            int stepSize = progressStatus.getStepSize();
            progressStatus.setStatusValue(progressStatus.getStatusValue() + (int)(stepSize / 5.));
            internationalization = new FLGInternationalization("freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.learningByDoing.internationalization",
                getClass().getClassLoader());
            primaryActivationButton = new FSLLearningUnitViewPrimaryActivationButton(loadImage("primaryActivationButton.gif"));
            primaryActivationButton.setToolTipText(internationalization.getString("button.primaryActivation.toolTipText"));
            elementsStructurePanel = new FLGLearningByDoingElementsStructurePanel();
            elementsStructurePanel.init(this, learningUnitEventGenerator, editMode);
            elementsStructurePanel.setAutomaticActivation(true);
            progressStatus.setStatusValue(progressStatus.getStatusValue() + (int)(stepSize / 5.));
            elementInteractionPanel = new FLGLearningByDoingElementInteractionPanel();
            elementInteractionPanel.init(this, learningUnitEventGenerator, editMode);
            progressStatus.setStatusValue(progressStatus.getStatusValue() + (int)(stepSize / 5.));
            elementsContentsPanel = new FLGLearningByDoingElementsContentsPanel();
            elementsContentsPanel.init(this, learningUnitEventGenerator, editMode);
            progressStatus.setStatusValue(progressStatus.getStatusValue() + (int)(stepSize / 5.));
            statusPanel = new FLGLearningByDoingStatusPanel();
            statusPanel.init(this, learningUnitEventGenerator, editMode);
            progressStatus.setStatusValue(progressStatus.getStatusValue() + (int)(stepSize / 5.));
    }

    public java.net.URL getMainHelpPageUrl() {
        return getClass().getClassLoader().getResource("freestyleLearningGroup/freestyleLearning/learningUnitViewManagers/learningByDoing/help");
    }

    public FSLLearningUnitViewPrimaryActivationButton getPrimaryActivationButton() {
        return primaryActivationButton;
    }

    protected Dispatcher createDispatcher() {
        Dispatcher d = FLGLearningByDoingDescriptor.newDispatcher();
        d.register(LearningByDoingDescriptor.class, FLGLearningByDoingDescriptor.class);
        d.register(ViewElement.class, FLGLearningByDoingElement.class);
        d.register(ViewElementLink.class, FLGLearningByDoingElementLink.class);
        d.register(ViewElementLinkTarget.class, FLGLearningByDoingElementLinkTarget.class);
        return d;
    }

    protected FSLLearningUnitViewXMLDocument createLearningUnitViewXMLDocument() {
        return new FLGLearningByDoingDescriptor();
    }

    private Image loadImage(String imageFileName) {
        return FLGImageUtility.loadImageAndWait(getClass().getClassLoader().getResource("freestyleLearningGroup/freestyleLearning/learningUnitViewManagers/learningByDoing/images/" +
            imageFileName));
    }
}
