// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.discussion;

/**
 * @see org.openuss.discussion.Forum
 */
public class ForumImpl
    extends org.openuss.discussion.ForumBase
	implements org.openuss.discussion.Forum
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -1086382949517313437L;

}