// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.discussion;

/**
 * @see org.openuss.discussion.Topic
 */
public class TopicImpl
    extends org.openuss.discussion.TopicBase
	implements org.openuss.discussion.Topic
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -3814745196487953634L;

}