/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.independent.gui.documents;

import java.awt.Toolkit;

import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

public class FLGLetterDocument extends PlainDocument {
    public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
        char[] source = str.toCharArray();
        char[] result = new char[source.length];
        int j = 0;
        for (int i = 0; i < result.length; i++) {
            if (Character.isLetter(source[i])) result[j++] = source[i];
            else {
                Toolkit.getDefaultToolkit().beep();
            }
        }
        super.insertString(offs, new String(result, 0, j), a);
    }

    public void setText(String str) {
        if (str != null) {
            char[] source = str.toCharArray();
            char[] result = new char[source.length];
            int j = 0;
            for (int i = 0; i < result.length; i++) {
                if (Character.isLetter(source[i])) result[j++] = source[i];
            }
            try {
                super.insertString(0, new String(result, 0, j), null);
            }
            catch (BadLocationException ble) { };
        }
    }
}
