// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.registration;

/**
 * @see org.openuss.registration.InstituteActivationCode
 */
public class InstituteActivationCodeImpl
    extends org.openuss.registration.InstituteActivationCodeBase
	implements org.openuss.registration.InstituteActivationCode
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5776719444824342051L;

}