// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.registration;

/**
 * @see org.openuss.registration.UserActivationCode
 */
public class UserActivationCodeImpl
    extends org.openuss.registration.UserActivationCodeBase
	implements org.openuss.registration.UserActivationCode
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3451344541090166257L;

}