/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.intro.data.xmlBindingSubclasses;

import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementLink;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementLinkTarget;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementsManager;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.intro.data.xmlBinding.ViewElementLink;

public class FLGIntroElementLink extends ViewElementLink implements FSLLearningUnitViewElementLink {
    public FSLLearningUnitViewElementLinkTarget
        addNewLearningUnitViewElementLinkTarget(String learningUnitId, String learningUnitViewManagerId,
        String learningUnitViewElementId) {
            FLGIntroElementLinkTarget learningUnitViewElementLinkTarget = new FLGIntroElementLinkTarget();
            return FSLLearningUnitViewElementsManager.addLearningUnitViewElementLinkTarget(this,
                learningUnitViewElementLinkTarget, learningUnitId, learningUnitViewManagerId, learningUnitViewElementId);
    }
}
