/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.independent.media;

public class FLGMediaException extends Exception {
    public FLGMediaException() {
        super("JMF Media Error!");
    }
}
