// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.search;

/**
 * @see org.openuss.search.LastEventProcessed
 */
public class LastEventProcessedImpl extends LastEventProcessedBase implements LastEventProcessed {
	/**
	 * The serial version UID of this class. Needed for serialization.
	 */
	private static final long serialVersionUID = 4747248044401399222L;

}