/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.notes.data.xmlBindungSubclasses;

import java.util.List;

import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementLink;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementLinkTarget;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementsManager;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.notes.data.xmlBinding.NoteLink;

public class FLGNoteElementLink extends NoteLink implements FSLLearningUnitViewElementLink {
    public FSLLearningUnitViewElementLinkTarget
        addNewLearningUnitViewElementLinkTarget(String learningUnitId, String learningUnitViewManagerId,
        String learningUnitViewElementId) {
            FLGNoteElementLinkTarget learningUnitViewElementLinkTarget = new FLGNoteElementLinkTarget();
            return FSLLearningUnitViewElementsManager.addLearningUnitViewElementLinkTarget(this,
                learningUnitViewElementLinkTarget, learningUnitId, learningUnitViewManagerId, learningUnitViewElementId);
    }

    public List getLearningUnitViewElementLinkTargets() {
        return getNoteLinkTargets();
    }
}
