/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.notes.data.xmlBindungSubclasses;

import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementLinkTarget;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.notes.data.xmlBinding.NoteLinkTarget;

public class FLGNoteElementLinkTarget extends NoteLinkTarget implements FSLLearningUnitViewElementLinkTarget {
}
