/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.notes.data.xmlBindungSubclasses;

import java.util.List;

import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewXMLDocument;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.notes.data.xmlBinding.NotesDescriptor;

public class FLGNotesDescriptor extends NotesDescriptor implements FSLLearningUnitViewXMLDocument {
    public List getLearningUnitViewElements() {
        return getNotes();
    }
}
