/* Generated by Freestyle Learning Group */

package freestyleLearning.homeCore.usersManager.data.xmlBindingSubclasses;

import freestyleLearning.homeCore.usersManager.data.xmlBinding.UsersDescriptor;

public class FSLUsersDescriptor extends UsersDescriptor {
}
