// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.mail;

/**
 * @see org.openuss.mail.MailMessage
 */
public class MailMessageImpl
    extends org.openuss.mail.MailMessageBase
	implements org.openuss.mail.MailMessage
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8970840249674910375L;

}