// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.mail;

/**
 * @see org.openuss.mail.MailToSend
 */
public class MailToSendImpl
    extends org.openuss.mail.MailToSendBase
	implements org.openuss.mail.MailToSend
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -2940053795663484199L;

}