// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.braincontest;

/**
 * @see org.openuss.braincontest.BrainContest
 */
public class BrainContestImpl
    extends org.openuss.braincontest.BrainContestBase
	implements org.openuss.braincontest.BrainContest
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5555579948326850568L;
    
    public String getAnswerCount(){
    	//TODO implement me
    	return "123/150";
    }

}