/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.questionAndAnswer.elementsStructurePanel;

import java.util.Date;

import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElement;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewManager;
import freestyleLearning.learningUnitViewAPI.elementsStructurePanel.FSLAbstractLearningUnitViewElementsStructurePanel;
import freestyleLearning.learningUnitViewAPI.events.learningUnitEvent.FSLLearningUnitEventGenerator;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.questionAndAnswer.data.xmlBindingSubclasses.FLGQuestionAndAnswerElement;

public class FLGQuestionAndAnswerElementsStructurePanel extends FSLAbstractLearningUnitViewElementsStructurePanel {
    public void init(FSLLearningUnitViewManager learningUnitViewManager,
        FSLLearningUnitEventGenerator learningUnitEventGenerator, boolean editMode) {
            super.init(learningUnitViewManager, learningUnitEventGenerator, editMode);
    }

    public void modifyLearningUnitViewElement(FSLLearningUnitViewElement element) {
        FLGQuestionAndAnswerElement questionAndAnswerElement = (FLGQuestionAndAnswerElement)element;
        questionAndAnswerElement.setLastModificationDate(String.valueOf(new Date().getTime()));
        if (!questionAndAnswerElement.getFolder()) {
            questionAndAnswerElement.setType(FLGQuestionAndAnswerElement.ELEMENT_TYPE_TEXT);
        }
        else {
            questionAndAnswerElement.setType(FLGQuestionAndAnswerElement.ELEMENT_TYPE_FOLDER);
        }
    }

    public FSLLearningUnitViewElement createLearningUnitViewElement(String id, String parentId, String title, boolean folder) {
        FLGQuestionAndAnswerElement newElement = new FLGQuestionAndAnswerElement();
        newElement.setId(id);
        newElement.setParentId(parentId);
        newElement.setTitle(title);
        newElement.setFolder(folder);
        newElement.setLastModificationDate(String.valueOf(new Date().getTime()));
        if (!folder) newElement.setType(FLGQuestionAndAnswerElement.ELEMENT_TYPE_TEXT);
        else
            newElement.setType(FLGQuestionAndAnswerElement.ELEMENT_TYPE_FOLDER);
        return newElement;
    }
}
