// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.internationalisation;

/**
 * @see org.openuss.internationalisation.Language
 */
public class LanguageImpl
    extends org.openuss.internationalisation.LanguageBase
	implements org.openuss.internationalisation.Language
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4893283772353544270L;

	public Long getId() {
		// TODO Auto-generated method stub
		return null;
	}

	public void setId(Long id) {
		// TODO Auto-generated method stub
		
	}

}