// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.security.externalAuth;

/**
 * @see org.openuss.security.externalAuth.SecurityDomain
 */
public class SecurityDomainImpl
    extends org.openuss.security.externalAuth.SecurityDomainBase
	implements org.openuss.security.externalAuth.SecurityDomain
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7124920159809163492L;

}