/* Generated by Freestyle Learning Group */

package freestyleLearning.learningUnitViewAPI.events.learningUnitViewEvent;

public class FSLLearningUnitViewVetoableAdapter extends FSLLearningUnitViewAdapter implements
    FSLLearningUnitViewVetoableListener {
        public void learningUnitViewElementActivating(FSLLearningUnitViewEvent event) { }

        public void learningUnitViewElementsRemoving(FSLLearningUnitViewEvent event) { }

        public void learningUnitViewSpecificEventOccurring(FSLLearningUnitViewEvent event) { }

        public void learningUnitViewDeactivating(FSLLearningUnitViewEvent event) { }
}
