/* Generated by Freestyle Learning Group */

package freestyleLearning.learningUnitViewAPI.events.learningUnitViewEvent;

public interface FSLLearningUnitViewVetoableListener extends FSLLearningUnitViewListener {
    void learningUnitViewElementActivating(FSLLearningUnitViewEvent event);

    void learningUnitViewElementsRemoving(FSLLearningUnitViewEvent event);

    void learningUnitViewSpecificEventOccurring(FSLLearningUnitViewEvent event);

    void learningUnitViewDeactivating(FSLLearningUnitViewEvent event);
}
