// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package org.openuss.foundation.lecture;

/**
 * @see org.openuss.foundation.lecture.Enrollment
 */
public class EnrollmentImpl
    extends org.openuss.foundation.lecture.EnrollmentBase
	implements org.openuss.foundation.lecture.Enrollment
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5670314763540215921L;

}