// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package org.openuss.foundation.lecture;

/**
 * @see org.openuss.foundation.lecture.Period
 */
public class PeriodImpl
    extends org.openuss.foundation.lecture.PeriodBase
	implements org.openuss.foundation.lecture.Period
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 9086031628022698697L;

}