/* Generated by Freestyle Learning Group */

package freestyleLearning.learningUnitViewAPI.events.learningUnitEvent;

public interface FSLLearningUnitVetoableListener extends FSLLearningUnitListener {
    void learningUnitActivating(FSLLearningUnitVetoableEvent event);

    void learningUnitCreating(FSLLearningUnitVetoableEvent event);

    void learningUnitsUserDirectoryChanging(FSLLearningUnitVetoableEvent event);
}
