/* Generated by Freestyle Learning Group */

package freestyleLearning.learningUnitViewAPI.events.learningUnitEvent;

public abstract class FSLLearningUnitAdapter implements FSLLearningUnitListener {
    public void learningUnitActivated(FSLLearningUnitEvent event) { }

    public void learningUnitCreated(FSLLearningUnitEvent event) { }

    public void learningUnitRemoved(FSLLearningUnitEvent event) { }

    public void learningUnitInvalidated(FSLLearningUnitEvent event) { }

    public void learningUnitEditModeChanged(FSLLearningUnitEvent event) { }

    public void learningUnitUserViewChanged(FSLLearningUnitEvent event) { }

    public void learningUnitsUserDirectoryChanged(FSLLearningUnitEvent event) { }
    
}
