/* Generated by Freestyle Learning Group */

package freestyleLearning.homeCore.usersManager.event;


public interface FSLUserEventGenerator {
    public void addUserListener(FSLUserListener listener);

    public void removeUserListener(FSLUserListener listener);
}
