/* Generated by Freestyle Learning Group */

package freestyleLearning.homeCore.usersManager.event;

public interface FSLUserVetoableListener extends FSLUserListener {
    void userChanging(FSLUserVetoableEvent userEvent);
}
