/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.questionAndAnswer.elementsContentsPanel;

import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementsManager;
import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewManager;
import freestyleLearning.learningUnitViewAPI.elementsContentsPanel.FSLAbstractLearningUnitViewElementContentPanel;
import freestyleLearning.learningUnitViewAPI.elementsContentsPanel.FSLAbstractLearningUnitViewElementsContentsPanel;
import freestyleLearning.learningUnitViewAPI.events.learningUnitEvent.FSLLearningUnitEventGenerator;
import freestyleLearning.learningUnitViewAPI.events.learningUnitViewEvent.FSLLearningUnitViewEvent;
import freestyleLearning.learningUnitViewAPI.events.learningUnitViewEvent.FSLLearningUnitViewVetoableAdapter;
import freestyleLearning.learningUnitViewAPI.util.FSLLearningUnitViewUtilities;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.questionAndAnswer.data.xmlBindingSubclasses.FLGQuestionAndAnswerElement;

public class FLGQuestionAndAnswerElementsContentsPanel extends FSLAbstractLearningUnitViewElementsContentsPanel {
    private FLGQuestionAndAnswerTextElementContentPanel[] textElementContentPanels;

    public void init(FSLLearningUnitViewManager learningUnitViewManager,
        FSLLearningUnitEventGenerator learningUnitEventGenerator, boolean editMode) {
            super.init(learningUnitViewManager, learningUnitEventGenerator, editMode);
            learningUnitViewManager.addLearningUnitViewListener(new FLGQuestionAndAnswer_LearningUnitViewAdapter());
            textElementContentPanels = new FLGQuestionAndAnswerTextElementContentPanel[2];
            textElementContentPanels[0] = new FLGQuestionAndAnswerTextElementContentPanel();
            textElementContentPanels[1] = new FLGQuestionAndAnswerTextElementContentPanel();
            for (int i = 0; i < 2; i++) {
                textElementContentPanels[i].init(learningUnitViewManager, learningUnitEventGenerator, editMode);
            }
    }

    public void setLearningUnitViewElementsManager(FSLLearningUnitViewElementsManager learningUnitViewElementsManager) {
        for (int i = 0; i < 2; i++) {
            textElementContentPanels[i].setLearningUnitViewElementsManager(learningUnitViewElementsManager);
        }
        super.setLearningUnitViewElementsManager(learningUnitViewElementsManager);
    }

    public void updateUI() {
        for (int i = 0; i < 2; i++) {
            if (textElementContentPanels != null) textElementContentPanels[i].updateUI();
        }
        super.updateUI();
    }

    protected FSLAbstractLearningUnitViewElementContentPanel
        getElementContentPanel(int index, String learningUnitViewElementId) {
            FLGQuestionAndAnswerElement learningUnitViewElement =
                (FLGQuestionAndAnswerElement)learningUnitViewElementsManager.getLearningUnitViewElement(learningUnitViewElementId, false);
            if (learningUnitViewElement != null) {
                if (learningUnitViewElement.getFolder()) {
                    return null;
                }
                else {
                    return textElementContentPanels[index];
                }
            }
            else
                return null;
    }

    class FLGQuestionAndAnswer_LearningUnitViewAdapter extends FSLLearningUnitViewVetoableAdapter {
        public void learningUnitViewElementLinksRemoved(FSLLearningUnitViewEvent event) {
            if (event.getLearningUnitViewManagerId().equals(learningUnitViewManager.getLearningUnitViewManagerId())) {
                FLGQuestionAndAnswerElement element = (FLGQuestionAndAnswerElement)learningUnitViewElementsManager.getLearningUnitViewElement(event.getLearningUnitViewElementId(), true);
                if (element.getHtmlFileName() != null) {
                    element.setHtmlFileName(FSLLearningUnitViewUtilities.updateExternalHtmlFilesOnLinksRemovedEvent(event,
                        learningUnitViewElementsManager, element, element.getHtmlFileName(),
                        FLGQuestionAndAnswerElement.ELEMENT_TYPE_TEXT, ".html"));
                }
            }
        }
    }
}
