/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.checkUp.data.xmlBindingSubclasses;

import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.checkUp.data.xmlBinding.RelatorStartPoint;

public class FLGCheckUpElementRelatorStartPoint extends RelatorStartPoint {
	public FLGCheckUpElementRelatorStartPoint deepCopy() {
		FLGCheckUpElementRelatorStartPoint copy = new FLGCheckUpElementRelatorStartPoint();
		copy.setHtmlFileName(getHtmlFileName());
		copy.setId(getId());
		return copy;
	}
}
