/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.checkUp.data.xmlBindingSubclasses;

import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.checkUp.data.xmlBinding.EvaluationsDescriptor;

public class FLGCheckUpEvaluationsDescriptor extends EvaluationsDescriptor {
}
