/* Generated by Freestyle Learning Group */

package freestyleLearning.learningUnitViewAPI.statusPanel;

import java.awt.*;
import javax.swing.*;

import freestyleLearning.learningUnitViewAPI.*;
import freestyleLearning.learningUnitViewAPI.events.learningUnitEvent.*;
import freestyleLearning.learningUnitViewAPI.events.learningUnitViewEvent.*;

abstract public class FSLAbstractLearningUnitViewStatusPanel extends JPanel implements FSLLearningUnitViewStatusPanel {
    protected boolean editMode;
    protected FSLLearningUnitViewManager learningUnitViewManager;
    protected FSLLearningUnitViewElementsManager learningUnitViewElementsManager;
    protected String activeLearningUnitViewElementId;
    protected String previousText;
    protected JLabel textLabel;

    public void init(FSLLearningUnitViewManager learningUnitViewManager,
        FSLLearningUnitEventGenerator learningUnitEventGenerator, boolean editMode) {
            this.learningUnitViewManager = learningUnitViewManager;
            this.editMode = editMode;
            learningUnitViewManager.addLearningUnitViewListener(new FSLLearningUnitViewStatusPanel_LearningUnitViewAdapter());
            buildIndependentUI();
    }
    
    protected void setText(String text) {
        textLabel.setText(text);
    }

    public void setLearningUnitViewElementsManager(FSLLearningUnitViewElementsManager learningUnitViewElementsManager) {
        this.learningUnitViewElementsManager = learningUnitViewElementsManager;
        activeLearningUnitViewElementId = null;
    }

    public void updateUI() {
        super.updateUI();
    }

    public void buildIndependentUI() {
        textLabel = new FSLLearningUnitViewStatusPanel_Label();
        setLayout(new BorderLayout());
        setOpaque(false);
        add(textLabel, BorderLayout.WEST);
//        buildDependentUI();
    }

    abstract public void buildDependentUI();
    
    protected class FSLLearningUnitViewStatusPanel_Label extends JLabel {
        public FSLLearningUnitViewStatusPanel_Label() {
            super();
            Font font = new Font("SansSerif", Font.PLAIN, 16);
            setFont(font);
            setOpaque(false);
        }
    }

    class FSLLearningUnitViewStatusPanel_LearningUnitViewAdapter extends FSLLearningUnitViewAdapter {
        public void learningUnitViewElementActivated(FSLLearningUnitViewEvent event) {
            if (event.getLearningUnitViewManagerId().equals(learningUnitViewManager.getLearningUnitViewManagerId())) {
                activeLearningUnitViewElementId = event.getActiveLearningUnitViewElementId();
                buildDependentUI();
            }
        }

        public void learningUnitViewActivated(FSLLearningUnitViewEvent event) {
            buildDependentUI();
        }

        public void learningUnitViewHyperlinkEntered(FSLLearningUnitViewEvent event) {
            previousText = textLabel.getText();
            textLabel.setText(event.getTargetLabel());
        }

        public void learningUnitViewHyperlinkExited(FSLLearningUnitViewEvent event) {
            textLabel.setText(previousText);
        }
    }
}
