/* Generated by Freestyle Learning Group */

package freestyleLearning.learningUnitViewAPI;

import java.awt.Image;

import freestyleLearning.learningUnitViewAPI.elementInteractionPanel.FSLLearningUnitViewElementInteractionButton;

public class FSLLearningUnitViewContextDependentActivationButton extends FSLLearningUnitViewElementInteractionButton {
    public FSLLearningUnitViewContextDependentActivationButton(Image image) {
        super(image);
    }
}
