/* Generated by Freestyle Learning Group */

package freestyleLearning.learningUnitViewAPI;

public interface FSLLearningUnitViewElementLinkTarget {
    String getTargetLearningUnitId();

    String getTargetLearningUnitViewManagerId();

    String getTargetLearningUnitViewElementId();

    void setTargetLearningUnitId(String targetLarningUnitId);

    void setTargetLearningUnitViewManagerId(String targetLarningUnitViewManagerId);

    void setTargetLearningUnitViewElementId(String targetLarningUnitViewElementId);
}
