/* Generated by Freestyle Learning Group */

package freestyleLearning.learningUnitViewAPI;


public interface FSLLearningUnitViewsActivator {
    void setActiveLearningUnitViewManager(FSLLearningUnitViewManager activeLearningUnitViewManager,
        boolean followingHyperlink);

    FSLLearningUnitViewManager getLearningUnitViewManager(String learningUnitViewManagerId);
    // Jan:

    /**
     * This method will return all ids and titles of the installed view
     * managers in a 2 dimensional array. The second index tells were the id
     * and the title will be found. A zero indicates the id and a one indicates the title.
     * @return the array containing the ids and the titles
     */
    String[] [] getInstalledLearningUnitViewManagersIdsAndTitles();
}
