// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package org.openuss.news;

/**
 * @see org.openuss.news.NewsCategory
 */
public class NewsCategoryImpl
    extends org.openuss.news.NewsCategoryBase
	implements org.openuss.news.NewsCategory
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -2889011664477329555L;

}