// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.security;

/**
 * @see org.openuss.security.UserProfile
 */
public class UserProfileImpl
    extends org.openuss.security.UserProfileBase
	implements org.openuss.security.UserProfile
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4978864423131642002L;

}