/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.independent.plotter;

/**
 * Ein <code>FLGPoint2D</code> repräsentiert einen Punkt <code>(x, y)</code> im Koordinatenraum,
 * spezifiziert mit <code>double</code> Präzision.<p> <code>FLGPoint2D</code> ist so einfach wie
 * m&ouml;glich gehalten und bietet keine Funktionalit&auml;t ausser der Speicherung eine
 * <i>x</i>- und einer <i>y</i>-Koordinate.
 * @see	FLGPolygon2D
 */
public class FLGPoint2D {
    private double x;
    private double y;

    /**
     * Erzeugt einen <code>FLGPoint2D</code> und initialisiert ihn mit <i>x</i> und <i>y</i>.
     * Die Koordinaten können nach der Erzeugung nicht mehr geändert werden.
     * @param	x	<i>x</i> Koordinate.
     * @param	y	<i>y</i> Koordinate.
     */
    public FLGPoint2D(double x, double y) {
        this.x = x;
        this.y = y;
    }

    /**
     * Liefert die <i>x</i> Koordinate dieses <code>FLGPoint2D</code>.
     * @return	die <i>x</i> Koordinate.
     */
    public double getX() { return x; }
    
    public void setX(double x) {
        this.x = x;
    }

    /**
     * Liefert die <i>y</i> Koordinate dieses <code>FLGPoint2D</code>.
     * @return	die <i>y</i> Koordinate.
     */
    public double getY() { return y; }
    
    public void setY(double y) {
        this.y = y;
    }

}
