DELETE FROM NEWS_CATEGORY;
COMMIT;
INSERT INTO NEWS_CATEGORY VALUES (0, 'newsCategory.ALL.Text');
INSERT INTO NEWS_CATEGORY VALUES (1, 'newsCategory.GLOBAL_ONLY.Text');
INSERT INTO NEWS_CATEGORY VALUES (2, 'newsCategory.DESKTOP_ONLY.Text');
INSERT INTO NEWS_CATEGORY VALUES (3, 'newsCategory.INSTITUTE_ONLY.Text');
INSERT INTO NEWS_CATEGORY VALUES (4, 'newsCategory.COURSE_ONLY.Text');
INSERT INTO NEWS_CATEGORY VALUES (5, 'newsCategory.INSTITUTE_COURSE.Text');
COMMIT;

