/* Generated by Freestyle Learning Group */

package freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.selector.data.xmlBindingSubclasses;

import freestyleLearning.learningUnitViewAPI.FSLLearningUnitViewElementLinkTarget;
import freestyleLearningGroup.freestyleLearning.learningUnitViewManagers.selector.data.xmlBinding.ViewElementLinkTarget;

/**
 * FLGSelectorElementLinkTarget.
 * Manager Class for Selector View Elements Link Targets.
 * @author Carsten Fiedler
 */
public class FLGSelectorElementLinkTarget extends ViewElementLinkTarget implements FSLLearningUnitViewElementLinkTarget {
}
