<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SynchronizationMessage"
    targetNamespace="http://cse.campussource.de/lsf/wsdl/SynchronizationMessage"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://cse.campussource.de/lsf/wsdl/SynchronizationMessage"
    xmlns:sync="http://cse.campussource.de/lsf/schema/SynchronizationMessage"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://cse.campussource.de/lsf/wsdl/SynchronizationMessage">
            <xsd:import namespace="http://cse.campussource.de/lsf/schema/SynchronizationMessage" schemaLocation="SynchronizationMessage.xsd"/>
        </xsd:schema>
    </types>
    <message name="performRequest">
        <part name="data" element="sync:synchronizationMessage"/>
    </message>
    <portType name="SynchronizationMessagePortType">
        <operation name="perform">
            <input name="input" message="tns:performRequest"/>            
        </operation>
    </portType>
    <binding name="SynchronizationMessageBinding" type="tns:SynchronizationMessagePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="perform">
            <soap:operation/>
            <input name="input">
                <soap:body use="literal"/>
            </input>
        </operation>
    </binding>
    <service name="SynchronizationMessageService">
        <port name="SynchronizationMessagePort" binding="tns:SynchronizationMessageBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/SynchronizationMessageService/SynchronizationMessagePort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="SynchronizationMessage">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="SynchronizationMessagePortTypeRole" portType="tns:SynchronizationMessagePortType"/>
    </plnk:partnerLinkType>
</definitions>
