alter table ASSISTANT drop constraint ASSISTANTIFKC;
alter table COURSE drop constraint FK76D5D41B210A53C6;
alter table PARTICIPANTS_COURSES drop constraint FK4E0995F9859EFF24;
alter table PARTICIPANTS_COURSES drop constraint FK4E0995F925625E37;
alter table PERSON drop constraint FK8C768F5564B1FE9C;
alter table STUDENT drop constraint STUDENTIFKC;
alter table STUDENT_MAINFIELDS drop constraint FKA3077A56B5A609BC;
drop table ADDRESS;
drop table ASSISTANT;
drop table COURSE;
drop table PARTICIPANTS_COURSES;
drop table PERSON;
drop table STUDENT;
drop table STUDENT_MAINFIELDS;
drop generator GLOBAL_SEQUENCE;
create table ADDRESS (ID numeric(18,0) not null, STREET varchar(255) not null, NUMBER integer not null, ZIPCODE numeric(18,0) not null, COUNTRY varchar(255) not null, primary key (ID));
create table ASSISTANT (ID numeric(18,0) not null, DEPARTMENT varchar(255) not null, primary key (ID));
create table COURSE (ID numeric(18,0) not null, NAME varchar(255) not null, MAXPARTICIPANTS integer not null, LECTURER_FK numeric(18,0) not null, primary key (ID));
create table PARTICIPANTS_COURSES (COURSES_FK numeric(18,0) not null, PARTICIPANTS_FK numeric(18,0) not null, primary key (COURSES_FK, PARTICIPANTS_FK));
create table PERSON (ID numeric(18,0) not null, FIRSTNAME varchar(255) not null, LASTNAME varchar(255) not null, REGISTRATION timestamp not null, ADDRESS_FK numeric(18,0) not null unique, primary key (ID));
create table STUDENT (ID numeric(18,0) not null, MNR numeric(18,0) not null unique, ENROLLMENT date not null, primary key (ID));
create table STUDENT_MAINFIELDS (STUDENT_FK numeric(18,0) not null, MAINFIELDS_FK varchar(255));
alter table ASSISTANT add constraint ASSISTANTIFKC foreign key (ID) references PERSON;
alter table COURSE add constraint FK76D5D41B210A53C6 foreign key (LECTURER_FK) references ASSISTANT;
alter table PARTICIPANTS_COURSES add constraint FK4E0995F9859EFF24 foreign key (COURSES_FK) references COURSE;
alter table PARTICIPANTS_COURSES add constraint FK4E0995F925625E37 foreign key (PARTICIPANTS_FK) references STUDENT;
alter table PERSON add constraint FK8C768F5564B1FE9C foreign key (ADDRESS_FK) references ADDRESS;
alter table STUDENT add constraint STUDENTIFKC foreign key (ID) references PERSON;
alter table STUDENT_MAINFIELDS add constraint FKA3077A56B5A609BC foreign key (STUDENT_FK) references STUDENT;
create generator GLOBAL_SEQUENCE;
