// OpenUSS - Open Source University Support System
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntityImpl.vsl in in openuss/tools/andromda/templates.
//
package org.openuss.paperSubmission;

/**
 * @see org.openuss.paperSubmission.Exam
 */
public class ExamImpl
    extends org.openuss.paperSubmission.ExamBase
	implements org.openuss.paperSubmission.Exam
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 532487035121850158L;

}